### ISSUE TITLE
SinglePath/SPScope breaks build on macOS

### ISSUE THREAD

**Issue by schoeberl** [t-crest/patmos-llvm#22]
Some new dependency break the build under macOS:

```
/Users/martin/t-crest/llvm/lib/Target/Patmos/SinglePath/SPScope.h:29:10: fatal error: 
      'boost/optional.hpp' file not found
#include "boost/optional.hpp"
```

**Comment by Emoun** [comment]
Could you provide me with where your boost implementation is and what version you are running of both clang and boost.

**Comment by schoeberl** [comment]
I actually don’t know where boost is installed on my machine, clang info here:

clang --version
Apple clang version 11.0.0 (clang-1100.0.33.16)
Target: x86_64-apple-darwin19.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Do you need that boost include file?

Martin

**Comment by Emoun** [comment]
The problem is that clang apparently can't find the boost installation on your machine.
It should be there, since its part of the Patmos installation guide. 
Could you check which boost packages you have installed with the following command and post the result:

```pkgutil --pkgs | grep "boost"```

**Comment by schoeberl** [comment]
Did not find any boost package :-( But I have is installed with homebrew. Mmh, as I remember pasim used probably boost as well. But I cannot check, as I first need the compiler running.

Martin

**Comment by Emoun** [comment]
The Patmos handbook specifies that boost is a requirement for the simulator. it is also specified as a dependency in the setup instructions, which is why I used it in my code.

I think you can check your homebrew boost installation with the command `brew list | grep "boost"`. If its not installed, I think you should get it and see if it fixes the issue.

I'm hesitant to stop using boost, as the only alternative is to switch to using C++17, which will probably introduce its own problems.

**Comment by Emoun** [comment]
I have tried building LLVM on a macOS virtual machine, and can confirm I have the same error as you.

This error is of course because clang can't find the standard boost installation. However, when I do manage to make it find boost (by editing cmake), I get a cryptic linking error where it seems to no longer be linking LLVM object files correctly.

I will update if/when I find a solution

**Comment by schoeberl** [comment]
Hi Emad,

BIG thanks for checking!

Maybe you do not really need boost? I am an anti-fan of boost. At one point it led to paasm not running with “just” 2 GB of memory.
An assembler! Stuff People did within a few KB before.

Did not look into the details, but are you using boost just to parse command line arguments? This could be done more lightweight
I guess (even manually).

Cheers,
Martin

**Comment by Emoun** [comment]
I have not done any command-line parsing, so if boost is used for that it's not me. But as far as I can see, boost isn't used elsewhere in the repo.

I use boost for code quality. E.g. most prominently I use the `optional<T>` construct. I'm hesitant to remove boost without a good alternative. The std library of C++17 might be a possible solution, but I'll have to investigate if we can safely switch to C++17.

**Comment by Emoun** [comment]
I looked into the use of C++17. 

We cannot easily switch to because `clang` will fail to compile. Additionally, it seems the LLVM project doesn't plan on switching to C++17 any time soon, as they [switched to C++14 just last year](http://lists.llvm.org/pipermail/llvm-dev/2019-April/131486.html). Therefore, as the LLVM policy so far prohibits C++17, it's probably best we stick with C++14 too.

I have also tried to make the current code work on mac, but  have been unsuccessful. When I do manage to import the boost library, the LLVM code stops linking for some reason.

Therefore, I will be removing the use of boost from my code.

**Comment by Emoun** [comment]
@schoeberl I have updated by fork of LLVM to no longer use boost. However, when I run it on my mac virtual machine, I still get a linking error that doesn't seem to be related to boost.
Could I get you to try and build using my fork and see if you get the same?
